### ISSUE TITLE
apparently, bug of the year of a 10th sub-release of python (2.7.10)

### ISSUE THREAD

**Issue by stonebig** [winpython/winpython#104]
winpython build process fails on the `cosmetic` history comparison file building ...
I may revert to 2.7.9 if I can't find out 
````
---------
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\WinPython-64bit-3.4.3.3_b0\winpython_github20150404\make.py", line 11
88, in make_all
    flavor=flavor)
  File "D:\WinPython-64bit-3.4.3.3_b0\winpython_github20150404\make.py", line 11
61, in make_winpython
    dist.make(remove_existing=remove_existing)
  File "D:\WinPython-64bit-3.4.3.3_b0\winpython_github20150404\make.py", line 10
61, in make
    flavor=self.flavor)
  File "D:\WinPython-64bit-3.4.3.3_b0\winpython_github20150404\diff.py", line 20
7, in write_changelog
    flavor=flavor)
  File "D:\WinPython-64bit-3.4.3.3_b0\winpython_github20150404\diff.py", line 18
1, in compare_package_indexes
    pi1 = PackageIndex(version1, rootdir=rootdir, flavor=flavor)
  File "D:\WinPython-64bit-3.4.3.3_b0\winpython_github20150404\diff.py", line 84
, in __init__
    self.from_file(basedir)
  File "D:\WinPython-64bit-3.4.3.3_b0\winpython_github20150404\diff.py", line 91
, in from_file
    self.from_text(text)
  File "D:\WinPython-64bit-3.4.3.3_b0\winpython_github20150404\diff.py", line 95
, in from_text
    assert version == self.version
AssertionError

````

**Comment by stonebig** [comment]
was indeed a sort of bug ... maybe should I modernize or suppress that part
