### ISSUE TITLE
Problems of Jupyter Lab (winpython version:Winpython64-3.10.5.0.exe)

### ISSUE THREAD

**Issue by superflq** [winpython/winpython#1089]
When I used the latest version and started Jupyter Lab.exe, I encountered such a prompt:
This problem did not appear in the old version.(Winpython64-3.8.8.0.exe)

[W 2022-07-20 21:11:46.692 ServerApp.jupyterlab_git] Fail to execute ['git', '--version']
    Traceback (most recent call last):
      File "D:\Python\python-3.10.5.amd64\lib\site-packages\jupyterlab_git\git.py", line 144, in execute
        code, output, error = await current_loop.run_in_executor(
      File "D:\Python\python-3.10.5.amd64\lib\concurrent\futures\thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "D:\Python\python-3.10.5.amd64\lib\site-packages\jupyterlab_git\git.py", line 110, in call_subprocess
        process = subprocess.Popen(
      File "D:\Python\python-3.10.5.amd64\lib\subprocess.py", line 969, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "D:\Python\python-3.10.5.amd64\lib\subprocess.py", line 1438, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] 系统找不到指定的文件

![20220720_211208_000](https://user-images.githubusercontent.com/35949104/179990701-081f55ff-4b5f-451a-b349-6fed3a2dbd3e.png)

**Comment by stonebig** [comment]
Strange..
Apparently you need to remove jupyterlab_git package

**Comment by stonebig** [comment]
hum, 
"jupyterlab_git" package fails because you have no git, so maybe removnig jupyterlabe_git is the solution.
next message is "dask_labextension" package... I may suggest you remove it, if it is also an issue after first one is removed.

**Comment by superflq** [comment]
> hum, "jupyterlab_git" package fails because you have no git, so maybe removing jupyterlab_git package is the solution. next message is "dask_labextension" package... I may suggest you remove it, if it is still an issue after first one is removed.


Thank you,Please consult again,How to remove jupyterab_ git package
I reinstalled the boot and still have this problem,
Is this the problem with the default installation package？

**Comment by stonebig** [comment]
Is there still a message with dask_labextension ? If yes remove this package too

**Comment by xungeer203** [comment]
> > hum, "jupyterlab_git" package fails because you have no git, so maybe removing jupyterlab_git package is the solution. next message is "dask_labextension" package... I may suggest you remove it, if it is still an issue after first one is removed.
> 
> 
> Thank you,Please consult again,How to remove jupyterab_ git package
> I reinstalled the boot and still have this problem,
> Is this the problem with the default installation package？

hi, have you found the solution to remove git package? I am not a software engineer...

**Comment by stonebig** [comment]
I may remove jupyterlab-git from next release

**Comment by stonebig** [comment]
I added this for jupyterlab,  but goal was to provide  simple experience, not complications

**Comment by stonebig** [comment]
removed
