### ISSUE TITLE
Need help building python

### ISSUE THREAD

**Issue by jwaisner** [winpython/winpython#1111]
@dev72 you mentioned downloading a new packager to fix #1109 . We think we we have it built right but our build.xml is failing on the pip upgrade step. Error shown below:

Our working branch is [here](https://github.com/Bearsampp/module-python/tree/Python_3.10.5)

```
 
   [delete] Deleting directory C:\Users\Jacob\Documents\GitHub\bearsampp\bearsampp-build\tmp\bundles_src\python\python3.10.5
    [mkdir] Created dir: C:\Users\Jacob\Documents\GitHub\bearsampp\bearsampp-build\tmp\bundles_src\python\python3.10.5
      [get] Destination already exists (skipping): C:\Users\Jacob\Documents\GitHub\bearsampp\bearsampp-build\tmp\bundles_src\python\Winpython64-3.10.5.0.7z
Setting project property: bundle.srcdest -> C:\Users\Jacob\Documents\GitHub\bearsampp\bearsampp-build\tmp/bundles_src/python/python3.10.5
Setting project property: bundle.srcfilename -> Winpython64-3.10.5.0.7z
     [echo] Processing Winpython64-3.10.5.0.7z...
Class org.apache.tools.ant.taskdefs.condition.Or loaded from parent loader (parentFirst)
Class org.apache.tools.ant.types.resources.selectors.Or loaded from parent loader (parentFirst)
Class org.apache.tools.ant.taskdefs.condition.Matches loaded from parent loader (parentFirst)
    [mkdir] Skipping C:\Users\Jacob\Documents\GitHub\bearsampp\bearsampp-build\tmp\bundles_src\python\python3.10.5 because it already exists.
     [exec] Current OS is Windows 11
     [exec] Executing 'C:\Users\Jacob\Documents\GitHub\bearsampp\dev\tools\7zip\7za.exe' with arguments:
     [exec] 'x'
     [exec] 'C:\Users\Jacob\Documents\GitHub\bearsampp\bearsampp-build\tmp/bundles_src/python/Winpython64-3.10.5.0.7z'
     [exec]
     [exec] The ' characters around the executable and arguments are
     [exec] not part of the command.
Execute:Java13CommandLauncher: Executing 'C:\Users\Jacob\Documents\GitHub\bearsampp\dev\tools\7zip\7za.exe' with arguments:
'x'
'C:\Users\Jacob\Documents\GitHub\bearsampp\bearsampp-build\tmp/bundles_src/python/Winpython64-3.10.5.0.7z'

The ' characters around the executable and arguments are
not part of the command.
     [exec] 
     [exec] 7-Zip (a) 21.04 beta (x86) : Copyright (c) 1999-2021 Igor Pavlov : 2021-11-02
     [exec]
     [exec] Scanning the drive for archives:
     [exec] 1 file, 813413170 bytes (776 MiB)
     [exec]
     [exec] Extracting archive: C:\Users\Jacob\Documents\GitHub\bearsampp\bearsampp-build\tmp\bundles_src\python\Winpython64-3.10.5.0.7z
     [exec] --
     [exec] Path = C:\Users\Jacob\Documents\GitHub\bearsampp\bearsampp-build\tmp\bundles_src\python\Winpython64-3.10.5.0.7z
     [exec] Type = 7z
     [exec] Physical Size = 813413170
     [exec] Headers Size = 1937809
     [exec] Method = Delta LZMA2:24 BCJ
     [exec] Solid = +
     [exec] Blocks = 7
     [exec]
     [exec] Everything is Ok
     [exec]
     [exec] Folders: 19717
     [exec] Files: 141349
     [exec] Size:       4245069385
     [exec] Compressed: 813413170
[available] Found file: C:\Users\Jacob\Documents\GitHub\bearsampp\bearsampp-build\tmp\bundles_src\python\python3.10.5\scripts\python.bat
fileset: Setup scanner in dir C:\Users\Jacob\Documents\GitHub\bearsampp\module-python\bin\python3.10.5 with patternSet{ includes: [] excludes: [] }
     [copy] Copying 9 files to C:\Users\Jacob\Documents\GitHub\bearsampp\bearsampp-build\tmp\bundles_src\python\python3.10.5
     [copy] Copying C:\Users\Jacob\Documents\GitHub\bearsampp\module-python\bin\python3.10.5\bearsampp.conf to C:\Users\Jacob\Documents\GitHub\bearsampp\bearsampp-build\tmp\bundles_src\python\python3.10.5\bearsampp.conf
     [copy] Copying C:\Users\Jacob\Documents\GitHub\bearsampp\module-python\bin\python3.10.5\bin\python.bat to C:\Users\Jacob\Documents\GitHub\bearsampp\bearsampp-build\tmp\bundles_src\python\python3.10.5\bin\python.bat
     [copy] Copying C:\Users\Jacob\Documents\GitHub\bearsampp\module-python\bin\python3.10.5\pyqt5\install.bat to C:\Users\Jacob\Documents\GitHub\bearsampp\bearsampp-build\tmp\bundles_src\python\python3.10.5\pyqt5\install.bat
     [copy] Copying C:\Users\Jacob\Documents\GitHub\bearsampp\module-python\bin\python3.10.5\pyqt5\pyqt5.properties to C:\Users\Jacob\Documents\GitHub\bearsampp\bearsampp-build\tmp\bundles_src\python\python3.10.5\pyqt5\pyqt5.properties
     [copy] Copying C:\Users\Jacob\Documents\GitHub\bearsampp\module-python\bin\python3.10.5\python-3.10.5\Lib\site-packages\PyQt5\qt.conf to C:\Users\Jacob\Documents\GitHub\bearsampp\bearsampp-build\tmp\bundles_src\python\python3.10.5\python-3.10.5\Lib\site-packages\PyQt5\qt.conf
     [copy] Copying C:\Users\Jacob\Documents\GitHub\bearsampp\module-python\bin\python3.10.5\python-3.10.5\qt.conf to C:\Users\Jacob\Documents\GitHub\bearsampp\bearsampp-build\tmp\bundles_src\python\python3.10.5\python-3.10.5\qt.conf
     [copy] Copying C:\Users\Jacob\Documents\GitHub\bearsampp\module-python\bin\python3.10.5\scripts\env.bat to C:\Users\Jacob\Documents\GitHub\bearsampp\bearsampp-build\tmp\bundles_src\python\python3.10.5\scripts\env.bat
     [copy] Copying C:\Users\Jacob\Documents\GitHub\bearsampp\module-python\bin\python3.10.5\settings\.pyzo\config.ssdf to C:\Users\Jacob\Documents\GitHub\bearsampp\bearsampp-build\tmp\bundles_src\python\python3.10.5\settings\.pyzo\config.ssdf
     [copy] Copying C:\Users\Jacob\Documents\GitHub\bearsampp\module-python\bin\python3.10.5\settings\winpython.ini to C:\Users\Jacob\Documents\GitHub\bearsampp\bearsampp-build\tmp\bundles_src\python\python3.10.5\settings\winpython.ini
     [echo] Upgrade PIP
     [exec] Current OS is Windows 11
     [exec] Executing 'C:\Users\Jacob\Documents\GitHub\bearsampp\bearsampp-build\tmp\bundles_src\python\python3.10.5\bin\python.bat' with arguments:
     [exec] '-m'
     [exec] 'pip'
     [exec] 'install'
     [exec] '--upgrade'
     [exec] 'pip'
     [exec]
     [exec] The ' characters around the executable and arguments are
     [exec] not part of the command.
Execute:Java13CommandLauncher: Executing 'C:\Users\Jacob\Documents\GitHub\bearsampp\bearsampp-build\tmp\bundles_src\python\python3.10.5\bin\python.bat' with arguments:
'-m'
'pip'
'install'
'--upgrade'
'pip'

The ' characters around the executable and arguments are
not part of the command.
     [exec] '"C:\Users\Jacob\Documents\GitHub\bearsampp\bearsampp-build\tmp\bundles_src\python\python3.10.5\python-3.10.5\python.exe"' is not recognized as an internal or external command,
     [exec] operable program or batch file.
  [antcall] Exiting C:\Users\Jacob\Documents\GitHub\bearsampp\module-python\build.xml.
  [antcall] Exiting C:\Users\Jacob\Documents\GitHub\bearsampp\module-python\build.xml.

BUILD FAILED
C:\Users\Jacob\Documents\GitHub\bearsampp\dev\build\build-bundle.xml:183: The following error occurred while executing this line:
C:\Users\Jacob\Documents\GitHub\bearsampp\dev\build\build-bundle.xml:154: The following error occurred while executing this line:
C:\Users\Jacob\Documents\GitHub\bearsampp\module-python\build.xml:34: exec returned: 1
        at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:675)
        at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:699)
        at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:527)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
        at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
        at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
        at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at java.base/java.util.Vector.forEach(Vector.java:1365)
        at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
        at net.sf.antcontrib.logic.IfTask$ElseIf.execute(IfTask.java:144)
        at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:211)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
        at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
        at org.apache.tools.ant.Main.runBuild(Main.java:818)
        at org.apache.tools.ant.Main.startAnt(Main.java:223)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)

Total time: 4 minutes 42 seconds
 Jacob@DESKTOP-2RB72UR  ~  Documents  GitHub  bearsampp  module-python  main   
>

```

**Comment by firai** [comment]
I don't really understand the reorganized folder structure in your script, but a couple of items to note based on the as-downloaded WinPython folder structure:
- As far as I'm aware, the scripts, including `python.bat` and the `env.bat` that it calls are written assuming the as-downloaded WinPython folder structure. It seems like `python.bat` and `env.bat` may been relocated in your setup, so it can't find `python.exe`. In general, if you want to run a Python module as a command, i.e. `python -m xxx`, such as `python -m pip`, you can directly call `python.exe` inside the `python-3.x.x.xxxxx` folder (such as `python-3.10.5.amd64`) rather than through `python.bat`.
- If you want to upgrade `pip` for whatever reason, you should use `upgrade_pip.bat` in the `scripts` folder. The Python script that the batch file calls applies a particular patch to `pip` to keep the Python distribution portable. Otherwise, all subsequent package installations with `pip` will be written with hardcoded paths.

**Comment by firai** [comment]
As a side note, I'm not a WinPython maintainer, but I understand that the WinPython copyright notice and license should be included in your license/list of copyrights if your fork is redistributing WinPython components.

**Comment by jwaisner** [comment]
Thank you. We have resolved this with a clean build of the repo and are able to build python with no error.
