### ISSUE TITLE
Problem upgrading Pandas and other modules in Winpython 3.7.12

### ISSUE THREAD

**Issue by stan3c** [winpython/winpython#1157]
So, I have quite a problem here. PC with Win7, downloaded Winpython 3.7.12 that has Pandas 1.2.5, but my code needs Pandas min v1.3.
I do not know what the issue is but Spyder and "WinPython Control Panel.exe" do not work. Nothing happens when I run them.
But that is not the biggest problem, as I could probably find a way round those problems. 
The thing is that I need Pandas min v1.3 and I am unable to upgrade this package.  Older versions of Winpython also have a problem updating Pandas to v1.3.
Which version of Winpython should I download to be able to have (or to be able to upgrade to) Pandas v1.3 AND have Spyder and control panel working out of the box on Win?
Is there a way to fix the upgrading pandas problem?

------------------------------------------------------------
D:\Work\WPy64-37120\scripts>pip3 install pandas==1.3.2 --upgrade
Collecting pandas==1.3.2
  Using cached pandas-1.3.2.tar.gz (4.7 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  pip subprocess to install build dependencies did not run successfully.
  exit code: 1

  [110 lines of output]
  Ignoring numpy: markers 'python_version == "3.8" and (platform_machine != "arm64" or platform_system != "Da
  Ignoring numpy: markers 'python_version >= "3.9" and (platform_machine != "arm64" or platform_system != "Da
  Ignoring numpy: markers 'python_version == "3.7" and platform_machine == "aarch64"' don't match your enviro
  Ignoring numpy: markers 'python_version == "3.8" and platform_machine == "aarch64"' don't match your enviro
  Ignoring numpy: markers 'python_version == "3.8" and platform_machine == "arm64" and platform_system == "Da
  Ignoring numpy: markers 'python_version == "3.9" and platform_machine == "arm64" and platform_system == "Da
  Collecting setuptools>=51.0.0
    Using cached setuptools-65.6.0-py3-none-any.whl (1.2 MB)
  Collecting wheel
    Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
  Collecting Cython<3,>=0.29.21
    Using cached Cython-0.29.32-py2.py3-none-any.whl (986 kB)
  Collecting numpy==1.17.3
    Using cached numpy-1.17.3.zip (6.4 MB)
    Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'done'
  Building wheels for collected packages: numpy
    Building wheel for numpy (setup.py): started
    Building wheel for numpy (setup.py): finished with status 'error'
    error: subprocess-exited-with-error

    python setup.py bdist_wheel did not run successfully.
    exit code: 1

    [15 lines of output]
    Running from numpy source directory.
    Traceback (most recent call last):
      File "<string>", line 36, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "C:\Users\admin\AppData\Local\Temp\pip-install-yp5_i23w\numpy_9ae4369ce3a44724a3332f13bc0eab1b\set
        setup_package()
      File "C:\Users\admin\AppData\Local\Temp\pip-install-yp5_i23w\numpy_9ae4369ce3a44724a3332f13bc0eab1b\set
        from numpy.distutils.core import setup
      File "C:\Users\admin\AppData\Local\Temp\pip-install-yp5_i23w\numpy_9ae4369ce3a44724a3332f13bc0eab1b\num
        from . import ccompiler
      File "C:\Users\admin\AppData\Local\Temp\pip-install-yp5_i23w\numpy_9ae4369ce3a44724a3332f13bc0eab1b\num
        from numpy.distutils import log
      File "C:\Users\admin\AppData\Local\Temp\pip-install-yp5_i23w\numpy_9ae4369ce3a44724a3332f13bc0eab1b\num
        from distutils.log import Log as old_Log
    ImportError: cannot import name 'Log'
    [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for numpy
    Running setup.py clean for numpy
    error: subprocess-exited-with-error

    python setup.py clean did not run successfully.
    exit code: 1

    [10 lines of output]
    Running from numpy source directory.

    `setup.py clean` is not supported, use one of the following instead:

      - `git clean -xdf` (cleans all files)
      - `git clean -Xdf` (cleans all versioned files, doesn't touch
                          files that aren't checked into the git repo)

    Add `--force` to your command to use it anyway if you must (unsupported).

    [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed cleaning build dir for numpy
  Failed to build numpy
  Installing collected packages: wheel, setuptools, numpy, Cython
    Running setup.py install for numpy: started
    Running setup.py install for numpy: finished with status 'error'
    error: subprocess-exited-with-error

    Running setup.py install for numpy did not run successfully.
    exit code: 1

    [24 lines of output]
    Running from numpy source directory.

    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:

      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install numpy`   (last NumPy release on PyPi)

    Traceback (most recent call last):
      File "<string>", line 36, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "C:\Users\admin\AppData\Local\Temp\pip-install-yp5_i23w\numpy_9ae4369ce3a44724a3332f13bc0eab1b\set
        setup_package()
      File "C:\Users\admin\AppData\Local\Temp\pip-install-yp5_i23w\numpy_9ae4369ce3a44724a3332f13bc0eab1b\set
        from numpy.distutils.core import setup
      File "C:\Users\admin\AppData\Local\Temp\pip-install-yp5_i23w\numpy_9ae4369ce3a44724a3332f13bc0eab1b\num
        from . import ccompiler
      File "C:\Users\admin\AppData\Local\Temp\pip-install-yp5_i23w\numpy_9ae4369ce3a44724a3332f13bc0eab1b\num
        from numpy.distutils import log
      File "C:\Users\admin\AppData\Local\Temp\pip-install-yp5_i23w\numpy_9ae4369ce3a44724a3332f13bc0eab1b\num
        from distutils.log import Log as old_Log
    ImportError: cannot import name 'Log'
    [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: legacy-install-failure

  Encountered error while trying to install package.

  numpy

  note: This is an issue with the package mentioned above, not pip.
  hint: See above for output from the failure.
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

pip subprocess to install build dependencies did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

D:\Work\WPy64-37120\scripts>pip install numpy
Requirement already satisfied: numpy in d:\work\wpy64-37120\pypy3.7-v7.3.7-win64\site-packages (1.21.4+mkl)

**Comment by stonebig** [comment]
Windows 7 is not supported, so suggestion that may not work : 
- download by hand pandas wheel , for example in c:\toto https://files.pythonhosted.org/packages/27/3d/ff72f600fdc626b8bf36dd426d122c0b6ac9e46d84f859d1620fb6f4ac0f/pandas-1.3.2-cp37-cp37m-win_amd64.whl
- then launch "WinPython Command Prompt.exe"
- then type "pip install c:\toto\pandas-1.3.2-cp37-cp37m-win_amd64.whl --upgrade --upgrade-strategy=only-if-needed"

**Comment by stonebig** [comment]
you would have better luck with a cPython-3.7, if this is what you want

**Comment by stonebig** [comment]
some say python-3.8 may still work on windows 7, so your last winpython hope, but limited to Pandas-1.2.4 until you update, would be https://sourceforge.net/projects/winpython/files/WinPython_3.8/3.8.9.0/

see https://github.com/winpython/winpython/blob/master/changelogs/WinPython-64bit-3.8.9.0.md
