### ISSUE TITLE
WinPython Control Panel fails to register WinPython in Windows 11

### ISSUE THREAD

**Issue by dfousek** [winpython/winpython#1224]
Hi !
I have a PC with a clean installation of Windows 11 and the Control Panel fails to register WinPython. I tried also the "Run as Administrator" way of running it but no success. There is no error appearing, but I kno from previous installations that a window "Successfully registered" appears after. Here, nothing happens.
Same behavior on a 2nd similar PC and WinPython versions 3.10 and 3.11
Bye,
Dimitri

**Comment by stonebig** [comment]
may you try with :
- click on "WinPython Command Prompt" icon
- type "wppm --register"

maybe it will give a clue

**Comment by stonebig** [comment]
succes is when you right click on a python program, and it proposes you to open it with python IDLE.

**Comment by dfousek** [comment]
Hi stonebig !

My path is: C:\PortableApps\WPy64-31110 and below follows the command's log: 

C:\PortableApps\WPy64-31110\scripts>wppm --register
Register distribution
(experimental)
This will associate file extensions, icons and
Windows explorer's context menu entries ('Edit with IDLE', ...)
with selected Python distribution in Windows registry.

Shortcuts for all WinPython launchers will be installed
in WinPython Start menu group (replacing existing
shortcuts).

Note: these actions are similar to those performed
when installing old Pythons with the official installer before 'py'
.

"C:\PortableApps\WPy64-31110\python-3.11.1.amd64\python.exe" -c "import sys; print(sys.maxsize > 2**32)"  *  C:\PortableApps\WPy64-31110\python-3.11.1.amd64
"C:\PortableApps\WPy64-31110\python-3.11.1.amd64\python.exe" -c "import sys;print(f'{sys.version_info.major}.{sys.version_info.minor}')"  *  C:\PortableApps\WPy64-31110\python-3.11.1.amd64
registering C:\PortableApps\WPy64-31110\python-3.11.1.amd64
continue ? Y/N
Y
"C:\PortableApps\WPy64-31110\python-3.11.1.amd64\python.exe" -c "import sys; print(sys.maxsize > 2**32)"  *  C:\PortableApps\WPy64-31110\python-3.11.1.amd64
"C:\PortableApps\WPy64-31110\python-3.11.1.amd64\python.exe" -c "import sys;print(f'{sys.version_info.major}.{sys.version_info.minor}')"  *  C:\PortableApps\WPy64-31110\python-3.11.1.amd64
"C:\PortableApps\WPy64-31110\python-3.11.1.amd64\python.exe" -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}')"  *  C:\PortableApps\WPy64-31110\python-3.11.1.amd64
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\PortableApps\WPy64-31110\python-3.11.1.amd64\Scripts\wppm.exe\__main__.py", line 7, in <module>
  File "C:\PortableApps\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\winpython\wppm.py", line 865, in main
    associate.register(dist.target)
  File "C:\PortableApps\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\winpython\associate.py", line 269, in register
    utils.create_shortcut(path, desc, fname)
  File "C:\PortableApps\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\winpython\utils.py", line 267, in create_shortcut
    ipf.Save(filename, 0)
pywintypes.com_error: (-2147024893, 'The system cannot find the path specified.', None, None)

C:\PortableApps\WPy64-31110\scripts>

**Comment by stonebig** [comment]
ok, suggestion:
- edit the file "C:\PortableApps\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\winpython\utils.py"
- add the line "print(f'ipf.save *{filename}*') " just before line 267
```
    print(f'ipf.save *{filename}*')    
    ipf.Save(filename, 0)
```

retry, and look what it says, in a normal world it is: 
```
ipf.save *C:\Users\user_windows_name\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\WinPython\IDLE (Python GUI).lnk*
ipf.save *C:\Users\user_windows_name\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\WinPython\IDLEX.lnk*
ipf.save *C:\Users\user_windows_name\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\WinPython\IPython Qt Console.lnk*
ipf.save *C:\Users\user_windows_name\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\WinPython\Jupyter Lab.lnk*
ipf.save *C:\Users\user_windows_name\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\WinPython\Jupyter Notebook.lnk*
ipf.save *C:\Users\user_windows_name\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\WinPython\Pyzo.lnk*
ipf.save *C:\Users\user_windows_name\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\WinPython\Qt Assistant.lnk*
ipf.save *C:\Users\user_windows_name\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\WinPython\Qt Designer.lnk*
ipf.save *C:\Users\user_windows_name\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\WinPython\Qt Linguist.lnk*
ipf.save *C:\Users\user_windows_name\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\WinPython\Spyder reset.lnk*
ipf.save *C:\Users\user_windows_name\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\WinPython\Spyder.lnk*
ipf.save *C:\Users\user_windows_name\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\WinPython\VS Code.lnk*
ipf.save *C:\Users\user_windows_name\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\WinPython\WinPython Command Prompt.lnk*
ipf.save *C:\Users\user_windows_name\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\WinPython\WinPython Control Panel.lnk*ipf.save *C:\Users\user_windows_name\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\WinPython\WinPython Interpreter.lnk*
ipf.save *C:\Users\user_windows_name\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\WinPython\WinPython Powershell Prompt.lnk*
ipf.save *C:\Users\user_windows_name\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\WinPython\WinPython Terminal.lnk*
```

**Comment by stonebig** [comment]
Nothing. But happy to see you happy now.
I may include the anti-wired crash in standard
