### ISSUE TITLE
Winpython control panel does not start in 3.10.11 and 3.11.3 from 2023-01. It does work in 3.10.9 from 2022-04

### ISSUE THREAD

**Issue by Olaf987** [winpython/winpython#1231]
Winpython control panel does not start in 3.10.11 and 3.11.3 from 2023.1. It does work in 3.10.9.

It is supposed to look like this:
`C:\Programs\WPy64-31090\scripts>python -m winpython.controlpanel
"C:\Programs\WPy64-31090\python-3.10.9.amd64\python.exe" -c "import sys; print(sys.maxsize > 2**32)"  *  C:\Programs\WPy64-31090\python-3.10.9.amd64
"C:\Programs\WPy64-31090\python-3.10.9.amd64\python.exe" -c "import sys;print(f'{sys.version_info.major}.{sys.version_info.minor}')"  *  C:\Programs\WPy64-31090\python-3.10.9.amd64`

But I get
`C:\Programs\WPy64-310110\scripts>python -m winpython.controlpanel
Traceback (most recent call last):
  File "C:\Programs\WPy64-310110\python-3.10.11.amd64\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Programs\WPy64-310110\python-3.10.11.amd64\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Programs\WPy64-310110\python-3.10.11.amd64\lib\site-packages\winpython\controlpanel.py", line 58, in <module>
    from winpython.qthelpers import (
  File "C:\Programs\WPy64-310110\python-3.10.11.amd64\lib\site-packages\winpython\qthelpers.py", line 218
    if isinstance(obj, str)
                           ^
SyntaxError: expected ':'`

and
`C:\Programs\WPy64-31130\scripts>python -m winpython.controlpanel
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Programs\WPy64-31130\python-3.11.3.amd64\Lib\site-packages\winpython\controlpanel.py", line 58, in <module>
    from winpython.qthelpers import (
  File "C:\Programs\WPy64-31130\python-3.11.3.amd64\Lib\site-packages\winpython\qthelpers.py", line 218
    if isinstance(obj, str)
                           ^
SyntaxError: expected ':'`

and nothing happens.

Do you know of any workarounds?

**Comment by stonebig** [comment]
fix is  on the line itself 

from:
` if isinstance(obj, str)`
to
 `if isinstance(icon, str):`

![image](https://github.com/winpython/winpython/assets/4312421/9f705445-8ef3-4fca-9651-f97dd7b56ef9)

**Comment by stonebig** [comment]
it's a stupid error. but it looks like a "post1" version is needed

**Comment by stonebig** [comment]
annoying papercut resolved with WinPython 2023-01 post1
