### ISSUE TITLE
pip are showing error when output unicode characters

### ISSUE THREAD

**Issue by NCNecros** [winpython/winpython#390]
When I search some in pip, I get error in output:

```
--- Logging error ---
Traceback (most recent call last):
  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\logging\__init__.py", line 982, in emit
    stream.write(msg)
  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\pip\_vendor\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\pip\_vendor\colorama\ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\pip\_vendor\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\encodings\cp866.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xf3' in position 43: character maps to <undefined>
Call stack:
  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\scripts\..\python-3.5.2.amd64\Scripts\pip.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\pip\__init__.py", line 221, in main
    return command.main(cmd_args)
  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\pip\commands\search.py", line 50, in run
    print_results(hits, terminal_width=terminal_width)
  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\pip\commands\search.py", line 128, in print_results
    logger.info(line)
Message: 'mysql_helper (1.0.0)                 - Um m\xf3dulo para auxiliar opera\xe7\xf5es com o\n                                       MySQL e MySQLdb'
Arguments: ()
```

**Comment by stonebig** [comment]
error with portuguese ?

**Comment by NCNecros** [comment]
I think with all unicode characters in description.
