### ISSUE TITLE
fail to run spyder under anaconda

### ISSUE THREAD

**Issue by woony90** [winpython/winpython#459]
Hi. I am new to Python and I need to install Anaconda 4.2.0 (Python 3.5 version) for academic purpose.
However, spyder won't open even being reset. Just for your information, I am using windows10.

I got the following message after typing "spyder --show-console" on anaconda prompt

(C:\Users\woony90\Anaconda3) C:\Users\woony90>spyder --show-console
Traceback (most recent call last):
  File "C:\Users\woony90\Anaconda3\lib\site-packages\qtpy\__init__.py", line 119, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ImportError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\woony90\Anaconda3\Scripts\spyder-script.py", line 5, in <module>
    sys.exit(spyder.app.start.main())
  File "C:\Users\woony90\Anaconda3\lib\site-packages\spyder\app\start.py", line 103, in main
    from spyder.app import mainwindow
  File "C:\Users\woony90\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 49, in <module>
    requirements.check_qt()
  File "C:\Users\woony90\Anaconda3\lib\site-packages\spyder\requirements.py", line 39, in check_qt
    import qtpy
  File "C:\Users\woony90\Anaconda3\lib\site-packages\qtpy\__init__.py", line 125, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

Can anybody help me with this issue?

Thanks!

**Comment by stonebig** [comment]
Well, maybe try with Winpython instead of Anaconda.

As a "alternative install experiment", I would suggest  Winpython-3.4  https://sourceforge.net/projects/winpython/files/WinPython_3.4/3.4.4.5/ may not interfer with your current Anaconda-3.5, and mostly work anywhere.
