### ISSUE TITLE
Building Winpython personal flavor: tutorial

### ISSUE THREAD

**Issue by DominiqueMakowski** [winpython/winpython#525]
I love winpython, but my only issue is that it's currently a bit too big (in size) 😕  Therefore, I'd like to build my own distribution, including the following packages:
- Spyder
- numpy
- pandas
- scipy
- matplotlib
- scikit-learn

How could I achieve that? I tried to install them on the Zero version but I failed installing spyder, numpy and scipy...

**Comment by stonebig** [comment]
There was a "slim" attempt a while ago to do this, but was not a giant success:
https://sourceforge.net/projects/winpython/files/WinPython_3.4/3.4.3.7/

For your case, you may experiment this (on python-3.5 or 3.6):
- start "winpython command prompt",
- type "pip download --dest  d:\toto PyQt5"
- type "pip download --dest  d:\toto scipy"
- type "pip download --dest  d:\toto matplotlib"
- type "pip download --dest  d:\toto pandas"
- type "pip download --dest  d:\toto spyder"
- type "pip download --dest  d:\toto scikit-learn"

- download numpy/scipy/pandas/Scikit-learn from cgohlke in this same directory "d:\toto" if you want speedier versions (but they shall be much bigger)
- then "pip install PyQt5 --no-index --trusted-host=None  --find-links=d:\toto"
- then "pip install scipy --no-index --trusted-host=None  --find-links=d:\toto"
- ....

zip the result and you have your own "tailor made" one

Please let me know if it works well / correct my  proposed procedure.

**Comment by DominiqueMakowski** [comment]
I followed your steps carefully:
1) downloaded 64bits 3.5 Zero version
2) installed it on my desktop
3) In the created directory, opened the winpython command prompt
4) ran `pip download --dest d:\toto PyQt5`. Now this created a "toto" folder on my D:/ drive, so I'm not sure if it was meant or if I had to replace the destination path with something else.
5) ran `pip download --dest d:\toto scipy`. This failed (the error log is pasted below). It says that I do not have visual C++, while in fact I've installed visual studio quite recently (like a month ago). Moreover, if I try to reinstall it it says that it's already installed...


-----------
### Error log:



```bash
C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\scripts>pip download --dest d:\toto scipy
Collecting scipy
  Downloading scipy-0.19.0.zip (15.3MB)
    100% |################################| 15.3MB 101kB/s
  Saved d:\toto\scipy-0.19.0.zip
    Complete output from command python setup.py egg_info:
    non-existing path in 'numpy\\distutils': 'site.cfg'
    Running from numpy source directory.
    C:\Users\Dom\AppData\Local\Temp\easy_install-ql4psxhc\numpy-1.12.1\setup.py:366: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    C:\Users\Dom\AppData\Local\Temp\easy_install-ql4psxhc\numpy-1.12.1\numpy\distutils\system_info.py:572: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    C:\Users\Dom\AppData\Local\Temp\easy_install-ql4psxhc\numpy-1.12.1\numpy\distutils\system_info.py:572: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      self.calc_info()
    C:\Users\Dom\AppData\Local\Temp\easy_install-ql4psxhc\numpy-1.12.1\numpy\distutils\system_info.py:572: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [blas_src]) or by setting
        the BLAS_SRC environment variable.
      self.calc_info()
    C:\Users\Dom\AppData\Local\Temp\easy_install-ql4psxhc\numpy-1.12.1\numpy\distutils\system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    C:\Users\Dom\AppData\Local\Temp\easy_install-ql4psxhc\numpy-1.12.1\numpy\distutils\system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
    C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\msvc.py", line 477, in __init__
        self.vc_ver = self.find_available_vc_vers()[-1]
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\command\bdist_egg.py", line 152, in run
        self.run_command("egg_info")
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Dom\AppData\Local\Temp\easy_install-ql4psxhc\numpy-1.12.1\numpy\distutils\command\egg_info.py", line 18, in run
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Dom\AppData\Local\Temp\easy_install-ql4psxhc\numpy-1.12.1\numpy\distutils\command\build_src.py", line 148, in run
      File "C:\Users\Dom\AppData\Local\Temp\easy_install-ql4psxhc\numpy-1.12.1\numpy\distutils\command\build_src.py", line 159, in build_sources
      File "C:\Users\Dom\AppData\Local\Temp\easy_install-ql4psxhc\numpy-1.12.1\numpy\distutils\command\build_src.py", line 294, in build_library_sources
      File "C:\Users\Dom\AppData\Local\Temp\easy_install-ql4psxhc\numpy-1.12.1\numpy\distutils\command\build_src.py", line 377, in generate_sources
      File "numpy\core\setup.py", line 663, in get_mathlib_info
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\distutils\command\config.py", line 243, in try_link
        self._check_compiler()
      File "C:\Users\Dom\AppData\Local\Temp\easy_install-ql4psxhc\numpy-1.12.1\numpy\distutils\command\config.py", line 51, in _check_compiler
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\distutils\_msvccompiler.py", line 197, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\msvc.py", line 172, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\msvc.py", line 771, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\msvc.py", line 480, in __init__
        raise distutils.errors.DistutilsPlatformError(err)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\sandbox.py", line 157, in save_modules
        yield saved
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
        yield
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\sandbox.py", line 255, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\sandbox.py", line 285, in run
        return func()
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\sandbox.py", line 253, in runner
        _execfile(setup_script, ns)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "C:\Users\Dom\AppData\Local\Temp\easy_install-ql4psxhc\numpy-1.12.1\setup.py", line 391, in <module>
        # from numpy.distutils, but after the MANIFEST removing and sdist import
      File "C:\Users\Dom\AppData\Local\Temp\easy_install-ql4psxhc\numpy-1.12.1\setup.py", line 383, in setup_package

      File "C:\Users\Dom\AppData\Local\Temp\easy_install-ql4psxhc\numpy-1.12.1\numpy\distutils\core.py", line 169, in setup
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\distutils\core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\command\easy_install.py", line 1106, in run_setup
        run_setup(setup_script, args)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\sandbox.py", line 258, in run_setup
        raise
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
        yield
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\sandbox.py", line 169, in save_modules
        saved_exc.resume()
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\sandbox.py", line 144, in resume
        six.reraise(type, exc, self._tb)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\sandbox.py", line 157, in save_modules
        yield saved
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
        yield
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\sandbox.py", line 255, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\sandbox.py", line 285, in run
        return func()
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\sandbox.py", line 253, in runner
        _execfile(setup_script, ns)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "C:\Users\Dom\AppData\Local\Temp\easy_install-ql4psxhc\numpy-1.12.1\setup.py", line 391, in <module>
        # from numpy.distutils, but after the MANIFEST removing and sdist import
      File "C:\Users\Dom\AppData\Local\Temp\easy_install-ql4psxhc\numpy-1.12.1\setup.py", line 383, in setup_package

      File "C:\Users\Dom\AppData\Local\Temp\easy_install-ql4psxhc\numpy-1.12.1\numpy\distutils\core.py", line 169, in setup
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\distutils\core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Dom\AppData\Local\Temp\pip-build-6hq3l3am\scipy\setup.py", line 416, in <module>
        setup_package()
      File "C:\Users\Dom\AppData\Local\Temp\pip-build-6hq3l3am\scipy\setup.py", line 412, in setup_package
        setup(**metadata)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\dist.py", line 317, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\dist.py", line 372, in fetch_build_eggs
        replace_conflicting=True,
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\pkg_resources\__init__.py", line 851, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\pkg_resources\__init__.py", line 1123, in best_match
        return self.obtain(req, installer)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\pkg_resources\__init__.py", line 1135, in obtain
        return installer(requirement)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\dist.py", line 440, in fetch_build_egg
        return cmd.easy_install(req)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\command\easy_install.py", line 674, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\command\easy_install.py", line 700, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\command\easy_install.py", line 881, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\command\easy_install.py", line 1120, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\lib\site-packages\setuptools\command\easy_install.py", line 1108, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Dom\AppData\Local\Temp\pip-build-6hq3l3am\scipy\
```

**Comment by stonebig** [comment]
hi again :
- "d:\toto" can be any other directory, it's just the place where you will pre-download  your wheels
- scipy error is my bad : I thought a compiled scipy was on pypi. it is NOT, so you have to download it from cgohlke (in d:\toto in my example).

Initial procedure changed

**Comment by DominiqueMakowski** [comment]
I did the following:

1. download [winpython Zero](http://winpython.github.io/) version
2. install it on desktop
3. In the created folder  open the winpython command prompt
4. create an empty folder somewhere (ex: `d:\temp`)
5. Download [numpy+mkl](http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy), [scipy](http://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy) and [scikit-learn](http://www.lfd.uci.edu/~gohlke/pythonlibs/#scikit-learn) and place them into the temp directory
6. Download other packages
   - `pip download --dest d:\temp PyQt5`
   - `pip download --dest d:\temp matplotlib`
   - `pip download --dest d:\temp pandas`
   - `pip download --dest d:\temp spyder`
7. Install them
   - run `pip install numpy --no-index --trusted-host=None --find-links=d:\temp`
   - run `pip install scipy --no-index --trusted-host=None --find-links=d:\temp`
   - run `pip install scikit-learn --no-index --trusted-host=None --find-links=d:\temp`
   - run `pip install PyQt5 --no-index --trusted-host=None --find-links=d:\temp`
   - run `pip install matplotlib --no-index --trusted-host=None --find-links=d:\temp`
   - run `pip install pandas --no-index --trusted-host=None --find-links=d:\temp`
   - run `pip install spyder --no-index --trusted-host=None --find-links=d:\temp`
8. zip the result and you have your own "tailor made" one

Unfortunately it failed at the end of the 7th step ( `pip install spyder --no-index --trusted-host=None --find-links=d:\temp`). Error log below.

Also, for matplotlib, pandas and spyder, is it possible to pip install them directly without first downloading them to the temp folder and then installing them?

------
```bash
  Running setup.py install for numpydoc ... done
  Running setup.py install for editdistance ... error
    Complete output from command C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Dom\\AppData\\Local\\Temp\\pip-build-vmhmwygs\\editdistance\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Dom\AppData\Local\Temp\pip-sb7bqfx3-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.5
    creating build\lib.win-amd64-3.5\editdistance
    copying editdistance\__init__.py -> build\lib.win-amd64-3.5\editdistance
    copying editdistance\_editdistance.h -> build\lib.win-amd64-3.5\editdistance
    copying editdistance\def.h -> build\lib.win-amd64-3.5\editdistance
    running build_ext
    building 'editdistance.bycython' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
Command "C:\Users\Dom\Desktop\WinPython-64bit-3.5.3.1Zero\python-3.5.3.amd64\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Dom\\AppData\\Local\\Temp\\pip-build-vmhmwygs\\editdistance\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Dom\AppData\Local\Temp\pip-sb7bqfx3-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Dom\AppData\Local\Temp\pip-build-vmhmwygs\editdistance\
``

**Comment by stonebig** [comment]
well you can remove "--no_index" to use wheels from pypi directly.

you apparently need to install vs C++ tools : 
[Microsoft Visual C++ Redistributable for Visual Studio 2015](https://www.visualstudio.com/downloads/download-visual-studio-vs#d-visual-c)

**Comment by DominiqueMakowski** [comment]
The thing is I already install it few weeks ago. I reinstalled the 2017 version following the link you provided, restarted my computer, but the same error appears 😞 

![untitled](https://cloud.githubusercontent.com/assets/8875533/25072017/69cfb2b6-22c5-11e7-825c-35170b12bbc9.png)

**Comment by stonebig** [comment]
hum, it seems it requires cython ("from Cython.Build import cythonize") . did you install cython before ?

**Comment by stonebig** [comment]
there is also the possibility it complains because you use visual studio c++ 2017 instead of 2015

**Comment by stonebig** [comment]
I may redo a Slim half-size version.

**Comment by stonebig** [comment]
the "editdistance" problem will go away soon : https://github.com/PyCQA/pylint/commit/a7e118d46f9866ce07a791e65c41b0655f22bacc

**Comment by DominiqueMakowski** [comment]
Sorry for the late answer. And thanks a lot for looking into my issue! It works when installing pylint==1.6.5. I've written the complete [steps](http://neurokit.readthedocs.io/en/latest/tutorials/Python.html) in my package's docs :)

thanks for maintining winpython,
cheers
