### ISSUE TITLE
Installing openpyxl and splinter without internet connection

### ISSUE THREAD

**Issue by bestickley** [winpython/winpython#600]
Hi, I have WinPython on Windows 7 (Python 3.6.3) and I've tried pip installing openpyxl and splinter, but I get an SSL Connection Error ( [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:777) ). So I tried downloading the .whl and .tar.gz files and pip installing via that way too. I got the same error. Now I've tried using python setup.py install while in the directory of the the tar.gz files but I'm still getting the same error. Is there any way to install a module without using the internet? It seems like it partly installs but then looks for package dependencies on pypi.org and that's when it errors out. I've also tried using (--trusted host). Please help. Thank you.

**Comment by stonebig** [comment]
if you have d:\toto\openpyxl‑2.5.0‑py2.py3‑none‑any.whl

(downloaded from https://www.lfd.uci.edu/~gohlke/pythonlibs/)
````
pip install  openpyxl‑2.5.0‑py2.py3‑none‑any.whl '--no-index --trusted-host=None --find-links=d:\toto 

````

**Comment by bestickley** [comment]
Thank you for the suggestion! I've tried it and this is what I get:

C:\WinPy\scripts>pip install openpyxl-2.5.0-py2.py3-none-any.whl '--no-index --trusted-host=None Invalid requirement: ''--no-index'
Traceback (most recent call last):
  File "C:\WinPy\python-3.6.3.amd64\lib\site-packages\pip\_vendor\packaging\requirements.py", line 92, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "C:\WinPy\python-3.6.3.amd64\lib\site-packages\pip\_vendor\pyparsing.py", line 1617, in parseString
    raise exc
  File "C:\WinPy\python-3.6.3.amd64\lib\site-packages\pip\_vendor\pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "C:\WinPy\python-3.6.3.amd64\lib\site-packages\pip\_vendor\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "C:\WinPy\python-3.6.3.amd64\lib\site-packages\pip\_vendor\pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "C:\WinPy\python-3.6.3.amd64\lib\site-packages\pip\_vendor\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "C:\WinPy\python-3.6.3.amd64\lib\site-packages\pip\_vendor\pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "C:\WinPy\python-3.6.3.amd64\lib\site-packages\pip\_vendor\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "C:\WinPy\python-3.6.3.amd64\lib\site-packages\pip\_vendor\pyparsing.py", line 3359, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "C:\WinPy\python-3.6.3.amd64\lib\site-packages\pip\_vendor\pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "C:\WinPy\python-3.6.3.amd64\lib\site-packages\pip\_vendor\pyparsing.py", line 2670, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\WinPy\python-3.6.3.amd64\lib\site-packages\pip\req\req_install.py", line 82, in __init__
    req = Requirement(req)
  File "C:\WinPy\python-3.6.3.amd64\lib\site-packages\pip\_vendor\packaging\requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at ""'--no""


C:\WinPy\scripts>pip install openpyxl-2.5.0-py2.py3-none-any.whl
Requirement already satisfied: openpyxl==2.5.0 from file:///C:/WinPy/scripts/openpyxl-2.5.0-py2.py3-none-any.whl in c:\winpy\ python-3.6.3.amd64\lib\site-packages\openpyxl-2.5.0-py3.6.egg
Collecting jdcal (from openpyxl==2.5.0)
  Could not fetch URL https://pypi.python.org/simple/jdcal/: There was a problem confirming the ssl certificate: [SSL: UNKNOW N_PROTOCOL] unknown protocol (_ssl.c:777) - skipping
  Could not find a version that satisfies the requirement jdcal (from openpyxl==2.5.0) (from versions: ) No matching distribution found for jdcal (from openpyxl==2.5.0)

**Comment by bestickley** [comment]
I have another computer that I can successfully install the package in. Is there any way I can install the modules into winpython on that computer and then transfer winpython over to my Win7 work computer for production?

**Comment by bestickley** [comment]
That did not work. 
Currently my plan is to download the latest Zero version of WinPython on my Windows 10 machine (where I have no problems with pip installing), then pip install openpyxl there, then copy and paste the whole WinPythonZero folder over to my Win 7 machine where I want to use openpyxl. Hopefully it will work.

**Comment by hiccup7** [comment]
@stonebig Did you comment originally have a single quote character at the end?  Maybe GitHub interpretted that character as MarkDown notation and then removed it.  This scenario could explain why @bestickley was getting an error when he executed your command line exactly.

**Comment by stonebig** [comment]
oups! you'r right:

bad:

````
pip install  openpyxl‑2.5.0‑py2.py3‑none‑any.whl '--no-index --trusted-host=None --find-links=d:\toto 

````

good:

````
pip install  openpyxl‑2.5.0‑py2.py3‑none‑any.whl --no-index --trusted-host=None --find-links=d:\toto 

````
