### ISSUE TITLE
Importing a binary extension module causes "ImportError: DLL load failed: Access is denied."

### ISSUE THREAD

**Issue by TylerGubala** [winpython/winpython#644]
Currently I am trying to author a native python module that builds Blender as a python module and adds the built python module to the library (as with many other modules).

The way that the library is built, all of the .dll files are placed alongside the .pyd file.

The way that the Blender python module is intended to work is that the .dll files need to be at the present working directory at the time the bpy.pyd is imported.

The file tree ends up looking like this when the module is installed:

```
venv\Lib\site-packages\bpy-1.2.0a2-py3.6-win-amd64.egg
                                                      |_ /__pycache__
                                                                     |_ /bpy.cpython-36.pyc
                                                      |_ /bpy.cp32-win_amd64.pyd
                                                                               |_/api-ms-win-core-console-l1-1-0.dll
                                                                               |_/api-ms-win-core-datetime-l1-1-0.dll
                                                                               |_/api-ms-win-core-debug-l1-1-0.dll
                                                                               |_/api-ms-win-core-errorhandling-l1-1-0.dll
                                                                               |_/ ... (More dll files)
                                                                               |_/bpy.pyd
                                                      |_ /EGG-INFO
                                                                  |_/dependency_links.txt
                                                                  |_/native_libs.txt
                                                                  |_/not-zip-safe
                                                                  |_/PKG-INFO
                                                                  |_/SOURCES.txt
                                                                  |_/top_level.txt
                                                      |_ /bpy.py
```

The tree (I think) ends up being more or less correct, based on a few stackoverflow questions (official documentation is surprisingly sparse!)

https://stackoverflow.com/questions/42585210/extending-setuptools-extension-to-use-cmake-in-setup-py

https://stackoverflow.com/questions/35497572/using-python-setuptools-to-put-cython-compiled-pyd-files-in-their-original-folde

However, after the built files are placed in site-packages, I enter my venv and try to import the bpy package, and receive the following error:

```
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import bpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\TGubs\Code\Python\blender_test\venv\lib\site-packages\bpy-1.2.0a2-py3.6-win-amd64.egg\bpy.py", line 7, in <module>
    __bootstrap__()
  File "C:\Users\TGubs\Code\Python\blender_test\venv\lib\site-packages\bpy-1.2.0a2-py3.6-win-amd64.egg\bpy.py", line 6, in __bootstrap__
    imp.load_dynamic(__name__,__file__)
  File "C:\Users\TGubs\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Access is denied.
```

What I think is very strange about this is that the bootstrapper module that was written for my package actually uses the depreciated method `_load(spec)` from `imp`!

Is my python module simply not written correctly? Or is this just because of the depreciation?

You can try this out yourself by running the following command:

`pip install bpy==1.2.0a1`

Thanks in advance!

**Comment by TylerGubala** [comment]
My issue was actually completely unrelated. All I had to do was make sure that the extension directory was created before `setuptools.command.build_ext.build_ext` did `run()`.

For some reason creating that directory suppressed `setuptools.command.build_ext.build_ext.run()` from attempting its own build.

Basically follow these instructions to the T:

https://stackoverflow.com/questions/42585210/extending-setuptools-extension-to-use-cmake-in-setup-py
