### ISSUE TITLE
Unregister distribution does not work

### ISSUE THREAD

**Issue by Aidolii** [winpython/winpython#710]
While you can register the distribution just fine, both with the Control Panel and with register_python.bat, you cannot unregister.

If you try to unregister with register_python.bat by running it twice (line 23 here: https://github.com/winpython/winpython/blob/master/scripts/register_python#L23)

```
Traceback (most recent call last):
  File "register_python", line 24, in <module>
    associate.register(args.target, current=not args.all)
  File "D:\WPy-3670\python-3.6.7.amd64\lib\site-packages\winpython\associate.py", line 143, in register
    utils.create_shortcut(path, desc, fname)
  File "D:\WPy-3670\python-3.6.7.amd64\lib\site-packages\winpython\utils.py", line 181, in create_shortcut
    ipf.Save(filename, 0)
pywintypes.com_error: (-2147024893, 'The system cannot find the path specified.', None, None)
```

This is broken in both 3.6 and 3.7 and I tried an older WinPython build from roughly a year ago so this has been broken for a while...

**Comment by stonebig** [comment]
hello @Aidolii 

This is the part that has not been touched since ages. You're welcomed to digg in the problem, has:
- there is currently no expertise in the project   https://github.com/winpython/winpython/issues/560,
- things have  evolved a bit in the world https://www.python.org/dev/peps/pep-0514/

It's unclear if the registration is something that:
- can be kept alive or not, 
- would need much more constraints and work to be allowed (like the py.exe thing).
