### ISSUE TITLE
WinPython fails as soon as it loads with UnicodeDecodeError

### ISSUE THREAD

**Issue by Code4SAFrankie** [winpython/winpython#792]
Started getting this error today, was working fine before then. Upgrade to Spacy 2.2.2 earlier with `.\python -m pip install --upgrade spacy`, not sure if that is related.

```
e:\WPy-3710\python-3.7.1.amd64>.\python.exe
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Failed calling sys.__interactivehook__.  See help(type) for accurate signature.
Traceback (most recent call last):
  File "e:\WPy-3710\python-3.7.1.amd64\lib\site.py", line 439, in register_readline
    readline.read_history_file(history)
  File "e:\WPy-3710\python-3.7.1.amd64\lib\site-packages\pyreadline\rlmain.py", line 165, in read_history_file
    self.mode._history.read_history_file(filename)
  File "e:\WPy-3710\python-3.7.1.amd64\lib\site-packages\pyreadline\lineeditor\history.py", line 82, in read_history_file
    for line in open(filename, 'r'):
  File "e:\WPy-3710\python-3.7.1.amd64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1748: character maps to <undefined>
>>> print('hello')
helloata and other attributes defined here:
>>> print('helloworld')
helloworld__ = None
```

**Comment by Code4SAFrankie** [comment]
Spacy upgrade installed the following, with the other module requirements having already been satisfied:

```
Installing collected packages: importlib-metadata, wasabi, thinc, spacy
  Found existing installation: importlib-metadata 0.19
    Uninstalling importlib-metadata-0.19:
      Successfully uninstalled importlib-metadata-0.19
  Found existing installation: wasabi 0.2.1
    Uninstalling wasabi-0.2.1:
      Successfully uninstalled wasabi-0.2.1
  Found existing installation: thinc 7.1.1
    Uninstalling thinc-7.1.1:
      Successfully uninstalled thinc-7.1.1
  Found existing installation: spacy 2.2.1
    Uninstalling spacy-2.2.1:
      Successfully uninstalled spacy-2.2.1
```

**Comment by stonebig** [comment]
pyreadline .... I guess you're in a graveyard

**Comment by stonebig** [comment]
I suggest you expose your issue in https://gitter.im/explosion/spaCy, as it doesn't look normal to me that pyreadline is still in use per Spacy

**Comment by Code4SAFrankie** [comment]
Thanks! Uninstalling pyreadline fixed it.
