### ISSUE TITLE
cannot import scipy with WinPython 2020-01 on Windows 10

### ISSUE THREAD

**Issue by makazhan** [winpython/winpython#828]
here's what I get in both Python 3.8.2 and 3.7.7 after executing ```import scipy```:

```
Traceback (most recent call last):

  File "<ipython-input-1-4363d2be0702>", line 1, in <module>
    import scipy

  File "C:\WPy64-3820\python-3.8.2.amd64\lib\site-packages\scipy\__init__.py", line 156, in <module>
    from . import fft

  File "C:\WPy64-3820\python-3.8.2.amd64\lib\site-packages\scipy\fft\__init__.py", line 76, in <module>
    from ._basic import (

  File "C:\WPy64-3820\python-3.8.2.amd64\lib\site-packages\scipy\fft\_basic.py", line 1, in <module>
    from scipy._lib.uarray import generate_multimethod, Dispatchable

  File "C:\WPy64-3820\python-3.8.2.amd64\lib\site-packages\scipy\_lib\uarray.py", line 27, in <module>
    from ._uarray import *

  File "C:\WPy64-3820\python-3.8.2.amd64\lib\site-packages\scipy\_lib\_uarray\__init__.py", line 114, in <module>
    from ._backend import *

  File "C:\WPy64-3820\python-3.8.2.amd64\lib\site-packages\scipy\_lib\_uarray\_backend.py", line 15, in <module>
    from . import _uarray  # type: ignore

ImportError: DLL load failed while importing _uarray: The specified module could not be found.

```

**Comment by stonebig** [comment]
Hum, that is strange. Are you on Windows 10 ?

**Comment by stonebig** [comment]
I found someone with the opposite problem ... maybe try the opposite, try with Anaconda

https://github.com/numpy/numpy/issues/12957#issuecomment-608414262

Another internet suggests maybe your path variable is too long

**Comment by dlzcn** [comment]
Run perfectly on my PC, but failed with same errors on my laptop. Both of them are running Windows 10. I checked length of the path variable on my PC, it is 1715 characters. Not sure the size of the variable on my laptop.

**Comment by stonebig** [comment]
Hum, maybe try your question on stackoverflow.

**Comment by stonebig** [comment]
are using pycharm ? https://github.com/psycopg/psycopg2/issues/1014#issuecomment-575524549

**Comment by stonebig** [comment]
hum, that may just be a python-3.8 change : now, Python- 3.8 doesn't look for a dll out of system unless explicitly told. 

as a blind guess, I suggest you retry with a python-3.7 distribution.

**Comment by dlzcn** [comment]
Switched to python-3.7 distriubtion.

File "D:\python\WPy64-3770\python-3.7.7.amd64\lib\site-packages\sklearn\__init__.py", line 82, in <module>
    from .base import clone
  File "D:\python\WPy64-3770\python-3.7.7.amd64\lib\site-packages\sklearn\base.py", line 20, in <module>
    from .utils import _IS_32BIT
  File "D:\python\WPy64-3770\python-3.7.7.amd64\lib\site-packages\sklearn\utils\__init__.py", line 20, in <module>
    from scipy.sparse import issparse
  File "D:\python\WPy64-3770\python-3.7.7.amd64\lib\site-packages\scipy\__init__.py", line 156, in <module>
    from . import fft
  File "D:\python\WPy64-3770\python-3.7.7.amd64\lib\site-packages\scipy\fft\__init__.py", line 76, in <module>
    from ._basic import (
  File "D:\python\WPy64-3770\python-3.7.7.amd64\lib\site-packages\scipy\fft\_basic.py", line 1, in <module>
    from scipy._lib.uarray import generate_multimethod, Dispatchable
  File "D:\python\WPy64-3770\python-3.7.7.amd64\lib\site-packages\scipy\_lib\uarray.py", line 27, in <module>
    from ._uarray import *
  File "D:\python\WPy64-3770\python-3.7.7.amd64\lib\site-packages\scipy\_lib\_uarray\__init__.py", line 114, in <module>
    from ._backend import *
  File "D:\python\WPy64-3770\python-3.7.7.amd64\lib\site-packages\scipy\_lib\_uarray\_backend.py", line 15, in <module>
    from . import _uarray  # type: ignore
ImportError: DLL load failed: The specified module could not be found.

**Comment by stonebig** [comment]
Well, I'm out of ideas at the moment

**Comment by dlzcn** [comment]
![2020-04-08 21_13_30](https://user-images.githubusercontent.com/37014191/78788555-9227bd80-79de-11ea-893c-01e849264f09.png)

It's VC runtime issue, happens one of them is missing from my PC. Fixed after installing the lastest file from https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads

Maybe need to update the instructions. Win10 users also need to pay attention to this requirement.

**Comment by makazhan** [comment]
> ![2020-04-08 21_13_30](https://user-images.githubusercontent.com/37014191/78788555-9227bd80-79de-11ea-893c-01e849264f09.png)
> 
> It's VC runtime issue, happens one of them is missing from my PC. Fixed after installing the lastest file from https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads
> 
> Maybe need to update the instructions. Win10 users also need to pay attention to this requirement.

Thanks! It fixed the issue on my laptop Win10 for both Python 3.7 and 3.8.

**Comment by stonebig** [comment]
hum, I include vcruntime140.dll . I may have missed some news ?

**Comment by stonebig** [comment]
So the vcruntime140_1.dll will be in next binaries, even if I'm not sure it solves the problem. 

It's a bit odd to have every user needing to install a microsoft executable.

**Comment by stonebig** [comment]
two actions done. Hope it will help. Thanks a lot @dlzcn for the inquiry. 

what tooldid you use to see the dll missing ? 

https://stackoverflow.com/questions/7378959/how-to-check-for-dll-dependency

**Comment by dlzcn** [comment]
> 
> what tool did you use to see the dll missing ? 
> 
> https://stackoverflow.com/questions/7378959/how-to-check-for-dll-dependency

I am using dependencies, you can fine it from https://lucasg.github.io/Dependencies/

**Comment by stonebig** [comment]
Ok, thanks again.
