### ISSUE TITLE
adodbapi is broken 

### ISSUE THREAD

**Issue by ZaitsevSergey** [winpython/winpython#83]
```
>>> import adodbapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\WinPython-32bit-2.7.9.4\python-2.7.9\lib\site-packages\adodbapi\__init__.py", line 10, in <module>
    from apibase import *
ImportError: No module named apibase
>>>
```

**Comment by stonebig** [comment]
oups!  me too on 3.4.3.3

**Comment by stonebig** [comment]
this bug (and workaround procedure)
https://mail.python.org/pipermail/python-win32/2014-May/013196.html

**Comment by stonebig** [comment]
ready in next release
