### ISSUE TITLE
error for use of pywrap_tensorflow.py

### ISSUE THREAD

**Issue by Sandy4321** [winpython/winpython#847]
to replicate try to use 
from nn import neural_net

from
https://github.com/harvitronix/reinforcement-learning-car

error is

File "e:\WINPYTHON_FULL_apr22\WPy64-3770\python-3.7.7.amd64\Lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
  from tensorflow.python.pywrap_tensorflow_internal import *
File "e:\WINPYTHON_FULL_apr22\WPy64-3770\python-3.7.7.amd64\Lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
  _pywrap_tensorflow_internal = swig_import_helper()
File "e:\WINPYTHON_FULL_apr22\WPy64-3770\python-3.7.7.amd64\Lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
  _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
File "e:\WINPYTHON_FULL_apr22\WPy64-3770\python-3.7.7.amd64\Lib\imp.py", line 242, in load_module
  return load_dynamic(name, filename, file)
File "e:\WINPYTHON_FULL_apr22\WPy64-3770\python-3.7.7.amd64\Lib\imp.py", line 342, in load_dynamic
  return _load(spec)

builtins.ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

File "e:\my_code\error_repo_git_hub_Apr26\reinforcement-learning-car-master\reinforcement-learning-car-master\playing.py", line 7, in <module>
  from nn import neural_net
File "e:\my_code\error_repo_git_hub_Apr26\reinforcement-learning-car-master\reinforcement-learning-car-master\nn.py", line 6, in <module>
  from keras.models import Sequential
File "e:\WINPYTHON_FULL_apr22\WPy64-3770\python-3.7.7.amd64\Lib\site-packages\keras\__init__.py", line 3, in <module>
  from . import utils
File "e:\WINPYTHON_FULL_apr22\WPy64-3770\python-3.7.7.amd64\Lib\site-packages\keras\utils\__init__.py", line 6, in <module>
  from . import conv_utils
File "e:\WINPYTHON_FULL_apr22\WPy64-3770\python-3.7.7.amd64\Lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
  from .. import backend as K
File "e:\WINPYTHON_FULL_apr22\WPy64-3770\python-3.7.7.amd64\Lib\site-packages\keras\backend\__init__.py", line 1, in <module>
  from .load_backend import epsilon
File "e:\WINPYTHON_FULL_apr22\WPy64-3770\python-3.7.7.amd64\Lib\site-packages\keras\backend\load_backend.py", line 90, in <module>
  from .tensorflow_backend import *
File "e:\WINPYTHON_FULL_apr22\WPy64-3770\python-3.7.7.amd64\Lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
  import tensorflow as tf
File "e:\WINPYTHON_FULL_apr22\WPy64-3770\python-3.7.7.amd64\Lib\site-packages\tensorflow\__init__.py", line 101, in <module>
  from tensorflow_core import *
File "e:\WINPYTHON_FULL_apr22\WPy64-3770\python-3.7.7.amd64\Lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
  from tensorflow.python.tools import module_util as _module_util
File "e:\WINPYTHON_FULL_apr22\WPy64-3770\python-3.7.7.amd64\Lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
  module = self._load()
File "e:\WINPYTHON_FULL_apr22\WPy64-3770\python-3.7.7.amd64\Lib\site-packages\tensorflow\__init__.py", line 44, in _load
  module = _importlib.import_module(self.__name__)
File "e:\WINPYTHON_FULL_apr22\WPy64-3770\python-3.7.7.amd64\Lib\importlib\__init__.py", line 127, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
File "e:\WINPYTHON_FULL_apr22\WPy64-3770\python-3.7.7.amd64\Lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
  from tensorflow.python import pywrap_tensorflow
File "e:\WINPYTHON_FULL_apr22\WPy64-3770\python-3.7.7.amd64\Lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
  raise ImportError(msg)

builtins.ImportError: Traceback (most recent call last):
File "e:\WINPYTHON_FULL_apr22\WPy64-3770\python-3.7.7.amd64\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
from tensorflow.python.pywrap_tensorflow_internal import *
File "e:\WINPYTHON_FULL_apr22\WPy64-3770\python-3.7.7.amd64\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
_pywrap_tensorflow_internal = swig_import_helper()
File "e:\WINPYTHON_FULL_apr22\WPy64-3770\python-3.7.7.amd64\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
File "e:\WINPYTHON_FULL_apr22\WPy64-3770\python-3.7.7.amd64\lib\imp.py", line 242, in load_module
return load_dynamic(name, filename, file)
File "e:\WINPYTHON_FULL_apr22\WPy64-3770\python-3.7.7.amd64\lib\imp.py", line 342, in load_dynamic
 ... (truncated)

**Comment by stonebig** [comment]
shall be same problem and solution than https://github.com/winpython/winpython/issues/828#issuecomment-611112600 . please confirm.

**Comment by Sandy4321** [comment]
great it works now
import message is
Using TensorFlow backend.
2020-04-27 16:20:36.151437: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-04-27 16:20:36.151712: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

**Comment by Sandy4321** [comment]
but I do have GPU in this comp?

**Comment by stonebig** [comment]
It's supposed to be a tensorflow_cpu inside WinPython

**Comment by Sandy4321** [comment]
1
so no way to use GPU?
2
what should be downloaded from 
https://visualstudio.microsoft.com/downloads/
to get the same as
x64: vc_redist.x64.exe
from
https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads
 is it 
Build Tools for Visual Studio 2019
These Build Tools allow you to build Visual Studio projects from a command-line interface. Supported projects include: ASP.NET, Azure, C++ desktop, ClickOnce, containers, .NET Core, .NET Desktop, Node.js, Office and SharePoint, Python, TypeScript, Unit Tests, UWP, WCF, and Xamarin

if yes there is not option for 64x
![image](https://user-images.githubusercontent.com/11426119/80513014-6ac47080-894c-11ea-9fb7-ecd91a4f9797.png)

**Comment by stonebig** [comment]
WinPython stopped shipping with tensorflow at the moment. and even Torch as it is too big... at the moment
