### ISSUE TITLE
installing additional winpython instance breaks old one

### ISSUE THREAD

**Issue by eflister** [winpython/winpython#96]
i had a winpython setup with a bunch of stuff installed to run https://pypi.python.org/pypi/sima, which worked.

i installed another winpython in another location and also installed sima, which worked.  but now, in my original winpython, if i try to run sima:
```

debugfile('C:/Users/nlab/Desktop/sima/examples/workflow.py', wdir='C:/Users/nlab/Desktop/sima/data/workflow_data')
> c:\users\nlab\desktop\sima\examples\workflow.py(9)<module>()
      8 
----> 9 """
     10 


ipdb> Traceback (most recent call last):

  File "<ipython-input-3-a7ff2ba315b9>", line 1, in <module>
    debugfile('C:/Users/nlab/Desktop/sima/examples/workflow.py', wdir='C:/Users/nlab/Desktop/sima/data/workflow_data')

  File "C:\Users\nlab\Downloads\WinPython-64bit-2.7.9.5\python-2.7.9.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 702, in debugfile
    debugger.run("runfile(%r, args=%r, wdir=%r)" % (filename, args, wdir))

  File "C:\Users\nlab\Downloads\WinPython-64bit-2.7.9.5\python-2.7.9.amd64\lib\bdb.py", line 400, in run
    exec cmd in globals, locals

  File "<string>", line 1, in <module>

  File "C:\Users\nlab\Downloads\WinPython-64bit-2.7.9.5\python-2.7.9.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 682, in runfile
    execfile(filename, namespace)

  File "C:\Users\nlab\Downloads\WinPython-64bit-2.7.9.5\python-2.7.9.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "c:/users/nlab/desktop/sima/examples/workflow.py", line 17, in <module>
    import sima

  File "C:\Users\nlab\Downloads\WinPython-64bit-2.7.9.5\python-2.7.9.amd64\lib\site-packages\sima\__init__.py", line 6, in <module>
    from sima.imaging import ImagingDataset

  File "C:\Users\nlab\Downloads\WinPython-64bit-2.7.9.5\python-2.7.9.amd64\lib\site-packages\sima\imaging.py", line 33, in <module>
    import sima.misc

  File "C:\Users\nlab\Downloads\WinPython-64bit-2.7.9.5\python-2.7.9.amd64\lib\site-packages\sima\misc\__init__.py", line 21, in <module>
    from skimage import transform as tf

  File "C:\Users\nlab\Downloads\WinPython-64bit-2.7.9.5\python-2.7.9.amd64\lib\site-packages\skimage\transform\__init__.py", line 3, in <module>
    from .hough_transform import hough_circle, hough_line_peaks

  File "C:\Users\nlab\Downloads\WinPython-64bit-2.7.9.5\python-2.7.9.amd64\lib\site-packages\skimage\transform\hough_transform.py", line 2, in <module>
    from scipy import ndimage

ImportError: cannot import name ndimage
```

**Comment by stonebig** [comment]
You should:
- replay (and note precisely), step by step, a third winpython installation next to you second one,
- at each step, relaunch (from spyder not started point) the second installation and check it still works, until it doesn't anymore,
- then post your notes here.
==> We should then know what step breaks your second installation, and maybe (maybe not) have a clue on what to do.

**Comment by eflister** [comment]
hrmph, now i can't reproduce it.  closing and reopening the original spyder makes it work.  in general i get a lot of flakiness from spyder -- it seems to randomly generate errors that get reported mainly as inability to import things (that previously worked in that session, with no intervening changes), but once closing and restarting it, sometimes work again.  is there an explanation for this?  i also installed onto OSX from macports, and there, stuff i can run fine from python at the cmd prompt won't run in spyder, again with import errors, but this one i can't get to go away by restarting spyder:

```
In [1]: import picos;picos.tools.available_solvers()
Out[1]: ['cvxopt', 'mosek7']

In [2]: runfile('/Users/eflister/sima/examples/workflow.py', wdir='/Users/eflister/sima')
Traceback (most recent call last):

  File "<ipython-input-2-4b36baecec87>", line 1, in <module>
    runfile('/Users/eflister/sima/examples/workflow.py', wdir='/Users/eflister/sima')

  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 682, in runfile
    execfile(filename, namespace)

  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 78, in execfile
    builtins.execfile(filename, *where)

  File "/Users/eflister/sima/examples/workflow.py", line 20, in <module>
    import sima

  File "sima/__init__.py", line 7, in <module>
    from sima.sequence import Sequence

  File "sima/sequence.py", line 68, in <module>
    from sima.motion._motion import _align_frame

  File "sima/motion/__init__.py", line 5, in <module>
    from .motion import MotionEstimationStrategy, ResonantCorrection

  File "sima/motion/motion.py", line 14, in <module>
    from . import _motion as mc

ImportError: cannot import name _motion
```

**Comment by stonebig** [comment]
I see there is some cython code in `sima`.

I'm not sure at all, but using the same `C:/Users/nlab/Desktop/sima` directory from different versions of winpython may be the problem.

**Comment by eflister** [comment]
different versions or different instances?  these are the same version of
winpython, just two instances.  the problems i'm describing w/importing
started before i installed the second instance, at first i thought it was a
sima bug and reported it here:
https://github.com/losonczylab/sima/issues/172

but then it didn't reproduce after restarting spyder (this was before
installing another instance)

and what about the osx issues?

**Comment by eflister** [comment]
oops -- ignore that osx stuff -- forgot that was from installing spyder directly, not winpython, sorry!

**Comment by stonebig** [comment]
two different versions, for example winpython-2.7.9.4 and winpython.2.7.9.5.

maybe we look in a wrong direction and the problem is in your PC:
- very low on RAM,
- a very agressive anti-virus,
- ... or you don't have really full rights on one of the directory you use
==> any other problem on this PC ?

A sometimes bug is also that a "\u" in a path is mis-interpreted as a the start of specification of a Unicode character.
==> you may do a 4th try by puting all your stuff in directories that don't have any  "/u" in their access path.

Sorry for osx, I can't help on this. I have the "feeling" that Mac is less friendly to spyder than windows and linux.

**Comment by stonebig** [comment]
I would suggest you register to "gitter sima" as indicated on the pypi sima page.

==> you may (perhaps) get more help with this dedicated chat line to sima people.

**Comment by eflister** [comment]
they think it is spyder

**Comment by stonebig** [comment]
So, you may try using `IDLE (Python GUI).exe` icon to check if it works better.

**Comment by eflister** [comment]
yeah, things work fine outside of spyder, i'll close this and move discussion to https://github.com/spyder-ide/spyder/issues/2450

**Comment by stonebig** [comment]
Thank you very much for the follow-up.
