### ISSUE TITLE
pip fails if there is a space in path

### ISSUE THREAD

**Issue by fnkr** [winpython/winpython#97]
This happens if you install a package, upgrade a package,
create a virtual environment using virtualenv, ...

```
[fnkr C:\Users\fnkr\Google Drive\Apps\Python] virtualenv env
Using base prefix 'C:\\Users\\fnkr\\Google Drive\\Apps\\Python\\WinPython-3.4.3.3-x64\\python-3.4.3.amd64'
New python executable in env\Scripts\python.exe
Installing setuptools, pip, wheel...
  Complete output from command C:\Users\fnkr\Goo...v\Scripts\python.exe -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel:
  Ignoring indexes: https://pypi.python.org/simple
Collecting setuptools
  The repository located at None is not a trusted or secure host and is being ignored. If this repository is available via HTTPS it is recommended to use HTTPS instead, otherwise you may silence this warning and allow it anyways with '--trusted-host None'.
  The repository located at None is not a trusted or secure host and is being ignored. If this repository is available via HTTPS it is recommended to use HTTPS instead, otherwise you may silence this warning and allow it anyways with '--trusted-host None'.
  The repository located at None is not a trusted or secure host and is being ignored. If this repository is available via HTTPS it is recommended to use HTTPS instead, otherwise you may silence this warning and allow it anyways with '--trusted-host None'.
  The repository located at None is not a trusted or secure host and is being ignored. If this repository is available via HTTPS it is recommended to use HTTPS instead, otherwise you may silence this warning and allow it anyways with '--trusted-host None'.
  The repository located at None is not a trusted or secure host and is being ignored. If this repository is available via HTTPS it is recommended to use HTTPS instead, otherwise you may silence this warning and allow it anyways with '--trusted-host None'.
  The repository located at None is not a trusted or secure host and is being ignored. If this repository is available via HTTPS it is recommended to use HTTPS instead, otherwise you may silence this warning and allow it anyways with '--trusted-host None'.
  Could not find a version that satisfies the requirement setuptools (from versions: )
No matching distribution found for setuptools
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "C:\Users\fnkr\Google Drive\Apps\Python\WinPython-3.4.3.3-x64\python-3.4.3.amd64\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\fnkr\Google Drive\Apps\Python\WinPython-3.4.3.3-x64\python-3.4.3.amd64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\fnkr\Google Drive\Apps\Python\WinPython-3.4.3.3-x64\python-3.4.3.amd64\Scripts\virtualenv.exe\__main__.py", line 9, in <module>
  File "C:\Users\fnkr\Google Drive\Apps\Python\WinPython-3.4.3.3-x64\python-3.4.3.amd64\lib\site-packages\virtualenv.py", line 832, in main
    symlink=options.symlink)
  File "C:\Users\fnkr\Google Drive\Apps\Python\WinPython-3.4.3.3-x64\python-3.4.3.amd64\lib\site-packages\virtualenv.py", line 1004, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "C:\Users\fnkr\Google Drive\Apps\Python\WinPython-3.4.3.3-x64\python-3.4.3.amd64\lib\site-packages\virtualenv.py", line 969, in install_wheel
    'PIP_NO_INDEX': '1'
  File "C:\Users\fnkr\Google Drive\Apps\Python\WinPython-3.4.3.3-x64\python-3.4.3.amd64\lib\site-packages\virtualenv.py", line 910, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command C:\Users\fnkr\Goo...v\Scripts\python.exe -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 1
```

If I move WinPython to a Path without a space in it it works so it seems like the space is the problem.

**Comment by stonebig** [comment]
Apparently, you have hit a very frequent bug, not related to Winpython, and applied the usual simple solution :
http://stackoverflow.com/questions/7911003/cant-install-via-pip-with-virtualenv
http://stackoverflow.com/questions/23569364/pip-does-not-exist-or-could-not-be-executed-within-virtualenv

==> You may close this issue as:
- it's not Winpython related,
- the space-in-the-path are a pain/bug-prone even under linux, so best is to avoid them.

**Comment by fnkr** [comment]
Thanks for your response!
